// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4VK83rGizySZ7cPEvWfPXrxlfXyPl94',
    appId: '1:615640516647:web:d9460eb05295d97525e602',
    messagingSenderId: '615640516647',
    projectId: 'servesmart-31630',
    authDomain: 'servesmart-31630.firebaseapp.com',
    storageBucket: 'servesmart-31630.firebasestorage.app',
    measurementId: 'G-96CGJBEM9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Gh-YSd6O8vu-TkF4pas78ufHu1yBisc',
    appId: '1:615640516647:android:0af387312c20192425e602',
    messagingSenderId: '615640516647',
    projectId: 'servesmart-31630',
    storageBucket: 'servesmart-31630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9grVUq9lzS5CNmjmCOmUexR3hKmV4Aq8',
    appId: '1:615640516647:ios:e0f3a68b57f54af525e602',
    messagingSenderId: '615640516647',
    projectId: 'servesmart-31630',
    storageBucket: 'servesmart-31630.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9grVUq9lzS5CNmjmCOmUexR3hKmV4Aq8',
    appId: '1:615640516647:ios:e0f3a68b57f54af525e602',
    messagingSenderId: '615640516647',
    projectId: 'servesmart-31630',
    storageBucket: 'servesmart-31630.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_4VK83rGizySZ7cPEvWfPXrxlfXyPl94',
    appId: '1:615640516647:web:dc28df21f4c4f54e25e602',
    messagingSenderId: '615640516647',
    projectId: 'servesmart-31630',
    authDomain: 'servesmart-31630.firebaseapp.com',
    storageBucket: 'servesmart-31630.firebasestorage.app',
    measurementId: 'G-VM6HNXYBB9',
  );
}
